[enb]
enb_id = 0x19C
mcc = 001
mnc = 01
mme_addr = 10.43.0.10
gtp_bind_addr = 10.43.0.40
s1c_bind_addr = 10.43.0.40
n_prb = 25
s1c_bind_port = 0

[rf]
dl_earfcn = 3350
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://ue:2001,id=enb,base_srate=11.52e6
tx_gain = 80
rx_gain = 40

[log]
all_level = info
filename = stdout
file_max_size = -1

[pcap]
enable = false
s1ap_enable = false

[gui]
enable = false
