[enb]
enb_id = 0x20B
mcc = 001
mnc = 01
mme_addr = 10.42.0.10
gtp_bind_addr = 10.42.0.1
s1c_bind_addr = 10.42.0.1
s1c_bind_port = 0
n_prb = 50

[rf]
device_name = uhd
device_args = type=x300,addr=192.168.10.2,clock=internal,time_source=internal,sampling_rate=11.52e6,lo_freq_offset_hz=11.52e6,send_frame_size=8000,recv_frame_size=8000,num_send_frames=64,num_recv_frames=64
tx_gain = 20
rx_gain = 31.5

[scheduler]
pdsch_max_mcs = 6
pusch_max_mcs = 4
nr_pdsch_mcs = 4
nr_pusch_mcs = 4

[expert]
nof_phy_threads = 3
metrics_period_secs = 1
metrics_csv_enable = true
metrics_csv_filename = /var/log/srsran/enb_metrics.csv
report_json_enable = true
report_json_filename = /var/log/srsran/enb_report.json

[log]
all_level = warning
rrc_level = info
filename = stdout
file_max_size = -1

[pcap]
enable = false
s1ap_enable = false

[gui]
enable = false
