[enb]
enb_id = 0x20A
mcc = 001
mnc = 01
mme_addr = 10.42.0.10
gtp_bind_addr = 10.42.0.30
s1c_bind_addr = 10.42.0.30
n_prb = 25

[rf]
device_name = uhd
device_args = type=x300,addr=192.168.10.2,clock=internal,time_source=internal
tx_gain = 0
rx_gain = 0

[log]
all_level = info
filename = /var/log/srsran/enb-x310.log
