[enb]
enb_id = 0x20A
mcc = 001
mnc = 01
mme_addr = 10.42.0.10
gtp_bind_addr = 10.42.0.1
s1c_bind_addr = 10.42.0.1
n_prb = 25
s1c_bind_port = 0

[rf]
dl_earfcn = 0
device_name = uhd
device_args = type=x300,addr=192.168.10.2,clock=internal,time_source=internal
tx_gain = 0
rx_gain = 0

[log]
all_level = info
filename = stdout
file_max_size = -1

[pcap]
enable = false
s1ap_enable = false

[gui]
enable = false
