CREATE DATABASE IF NOT EXISTS ims;
USE ims;
CREATE TABLE IF NOT EXISTS subscribers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  imsi VARCHAR(15) NOT NULL UNIQUE,
  msisdn VARCHAR(32),
  impi VARCHAR(128) NOT NULL,
  impu VARCHAR(128) NOT NULL,
  domain_name VARCHAR(128) NOT NULL,
  auth_ha1 VARCHAR(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
